### ISSUE TITLE
depends on a version of nodegit that triggers a 5+ min source compile on install

### ISSUE THREAD

**Issue by beatthat** [strugee/node-git-clone-or-pull#16] opened 2017-09-16 20:21 UTC
Super useful utility but encountering this problem on install:

git-clone-or-pull@3.0.0 depends on nodegit@0.19.0

Unfortunately, that version of nodegit (maybe newly?) fails to download prebuilt libs and then triggers a source build that takes 5+ min on every install.

I forked git-clone-or-pull and upgraded nodegit to 0.20.2 and that fixes the issue on my env:

https://github.com/beatthat/node-git-clone-or-pull

In case it matters here are env details:

OSX - 10.12.6
npm - 5.3.0

Thanks again for useful package!

**Comment by strugee** [comment] 2017-09-17 00:39
> Thanks again for useful package!

Sure thing!

Duplicate of #15 though :)

**Closed as completed by strugee** 2017-09-17 00:39 UTC
